---
- name: install Docker
  hosts: control
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Create new directory
      file:
        path: /tmp/dockDeploy
        state: directory
    - name: Copy war file
      copy:
       src: /var/lib/jenkins/workspace/addressbook/addressbook_main/target/addressbook.war
       dest: /tmp/dockDeploy/
    - name: Copy Dockerfile
      copy:
       src: /etc/ansible/Dockerfile
       dest: /tmp/dockDeploy/
    - name: Build Docker Image
      command: chdir=/tmp/dockDeploy/ docker build . -t edureka/inclass
    - name: Run Docker Container
      command: chdir=/tmp/dockDeploy/ docker run -it -d -p 9000:8080 edureka/inclass
